### ISSUE TITLE
tsml_ui when enabled part of the left hand side is covered by a black bar

### ISSUE THREAD

**Issue by virtualtom** [code4recovery/tsml-ui#364] opened 2024-02-21 21:34 UTC
It looks like the left sidebar of my theme reappears (but has no links).

This doesn't happen in the legacy UI and may have happened in the last 12 Step Plugin update.

The site is buffaloaany.org but it is set to legacy right now

I'm using the twenty fourteen theme from Wordpress

**Comment by gkovats** [comment] 2024-02-21 22:06
Hi @virtualtom can you supply a screenshot of the issue?

**Comment by gkovats** [comment] 2024-02-21 22:12
Also, worth trying to grab the latest plugin - there was a fix today that made the TSML-UI 100% width, which _may_ address what you were seeing? Worth a shot.

**Comment by joshreisner** [comment] 2024-02-21 22:20
looks like they are running the twentyfourteen theme - i noticed this recently - we used to hide the sidebar using CSS but it doesn't seem to be working now. not sure what caused the regression

**Comment by virtualtom** [comment] 2024-02-21 22:20
Hi George,

I’m at version 3.14.32.  Here’s a screenshot in legacy and tsml_ui

￼

￼

**Comment by joshreisner** [comment] 2024-02-21 22:29
hopefully should be fixed now - not sure when / how we lost this theme override, that was in there for a long time

**Comment by virtualtom** [comment] 2024-02-21 23:54
I’ll check for the update and verify it for youThanks!TomOn Feb 21, 2024, at 5:29 PM, Josh Reisner ***@***.***> wrote:﻿
hopefully should be fixed now - not sure when / how we lost this theme override, that was in there for a long time

**Comment by virtualtom** [comment] 2024-02-22 01:30
That fixed it

**Closed** 2024-02-22 01:31 UTC
