### ISSUE TITLE
Random Errors in Google Chrome

### ISSUE THREAD

**Issue by richieboo** [code4recovery/tsml-ui#419] opened 2024-10-01 01:05 UTC
Is there a way I can load an uncompressed version of app.js so that I can try to help you guys identify what it is trying to remove? Below is error console and below that is a link video of how I can create the error. Thanks!

```Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at fl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1127078)
    at pl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1126782)
    at fl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1127541)
    at pl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1126782)
    at fl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1127865)
    at gl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1128353)
    at _l (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1129931)
    at gl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1128503)
    at _l (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1128616)
    at gl (https://tsml-ui.code4recovery.org/app.js?ver=6.6.2:2:1128503)
```

https://github.com/user-attachments/assets/95f5dc9b-6c59-45a4-b990-ed4f8e6c58af

**Comment by joshreisner** [comment] 2024-10-01 01:22
hm i'm not sure how to do that - maybe check out and the code locally? we've got some instructions on how to do that here: https://github.com/code4recovery/tsml-ui/?tab=readme-ov-file#contributing

i'm not seeing chrome errors on websites like aasanjose.org/meetings or aasfmarin.org/meetings - although i'm not seeing errors on aasj.org/meetings either in chrome

but it seems like you're doing a lot of asynchronmous customization after the meeting page renders - i'm assuming if you try turning that off temporarily that it will not throw that error?

<img width="396" alt="Screenshot 2024-09-30 at 6 17 35 PM" src="https://github.com/user-attachments/assets/c234c335-c5fc-45ba-b954-c291faa62cd5">

perhaps you could create a separate page with no customizations so we can see if that is the cause?

**Comment by joshreisner** [comment] 2024-10-01 01:34
i think it's the `reformatMeetingPage` function specifically - looks like you're calling a `p.remove()` which i'm guessing is where the error is coming from

would be way less work i think to just fork TSML UI?

**Comment by joshreisner** [comment] 2024-10-06 13:24
going to close the issue - lmk if we help though

**Closed by joshreisner** 2024-10-06 13:24 UTC
